# Generated by Django 2.2.10 on 2020-11-19 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201118_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='anonymous',
        ),
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 10, 57, 42, 951852)),
        ),
    ]
