# Generated by Django 2.2.10 on 2020-11-19 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20201119_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 11, 48, 49, 955228)),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_type',
            field=models.CharField(default='text', max_length=5),
        ),
    ]
