# Generated by Django 2.2.10 on 2020-11-19 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20201119_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 13, 7, 48, 211384)),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_type',
            field=models.CharField(choices=[('text', 't'), ('radio', 'r'), ('check', 'c')], default='t', max_length=5),
        ),
    ]
