# Generated by Django 2.2.10 on 2020-11-19 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20201119_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='title',
            new_name='choice',
        ),
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 21, 58, 25, 514744)),
        ),
    ]
